// Copyright Xeno Innovations, Inc. 2025
// See the LICENSE file in the project root for more information.

// <Auto-Generated>This is here so CodeMaid doesn't reorganize this document.</Auto-Generated>
using System;

namespace Lite.StateMachine;

public struct StateMap<TStateId>
  where TStateId : struct, Enum
{
  public TStateId? OnSuccess;
  public TStateId? OnError;
  public TStateId? OnFailure;
}
